# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\pythonProject\ui\SearchPeople.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearcPeopleWindow(object):
    def setupUi(self, SearcPeopleWindow):
        SearcPeopleWindow.setObjectName("SearcPeopleWindow")
        SearcPeopleWindow.resize(900, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("..\\pythonProject\\ui\\../Картинки/bank_78392.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SearcPeopleWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SearcPeopleWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 881, 751))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.search_field = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.search_field.setFont(font)
        self.search_field.setObjectName("search_field")
        self.gridLayout.addWidget(self.search_field, 1, 1, 1, 3)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.search_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.search_button.setFont(font)
        self.search_button.setObjectName("search_button")
        self.gridLayout.addWidget(self.search_button, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 2, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.toolButton.setFont(font)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 1, 5, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 3, 1, 1, 4)
        SearcPeopleWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SearcPeopleWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        SearcPeopleWindow.setMenuBar(self.menubar)
        self.action_2 = QtWidgets.QAction(SearcPeopleWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(SearcPeopleWindow)
        self.action_3.setObjectName("action_3")
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(SearcPeopleWindow)
        QtCore.QMetaObject.connectSlotsByName(SearcPeopleWindow)

    def retranslateUi(self, SearcPeopleWindow):
        _translate = QtCore.QCoreApplication.translate
        SearcPeopleWindow.setWindowTitle(_translate("SearcPeopleWindow", "Search People Window"))
        self.search_field.setPlaceholderText(_translate("SearcPeopleWindow", "Phone number"))
        self.label.setText(_translate("SearcPeopleWindow", "Поиск: "))
        self.search_button.setText(_translate("SearcPeopleWindow", "Искать"))
        self.toolButton.setText(_translate("SearcPeopleWindow", "..."))
        self.menu.setTitle(_translate("SearcPeopleWindow", "Настройки"))
        self.action_2.setText(_translate("SearcPeopleWindow", "Просмотр пользователй"))
        self.action_3.setText(_translate("SearcPeopleWindow", "Настройки пользователя"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SearcPeopleWindow = QtWidgets.QMainWindow()
    ui = Ui_SearcPeopleWindow()
    ui.setupUi(SearcPeopleWindow)
    SearcPeopleWindow.show()
    sys.exit(app.exec_())
