# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\LB2\ui\autho.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Autho(object):
    def setupUi(self, Autho):
        Autho.setObjectName("Autho")
        Autho.resize(800, 228)
        self.centralwidget = QtWidgets.QWidget(Autho)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.login = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 3)
        Autho.setCentralWidget(self.centralwidget)

        self.retranslateUi(Autho)
        QtCore.QMetaObject.connectSlotsByName(Autho)

    def retranslateUi(self, Autho):
        _translate = QtCore.QCoreApplication.translate
        Autho.setWindowTitle(_translate("Autho", "MainWindow"))
        self.login.setPlaceholderText(_translate("Autho", "phone number"))
        self.label_2.setText(_translate("Autho", "Пароль"))
        self.password.setPlaceholderText(_translate("Autho", "name"))
        self.label.setText(_translate("Autho", "Логин"))
        self.pushButton.setText(_translate("Autho", "Авторизоваться"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Autho = QtWidgets.QMainWindow()
    ui = Ui_Autho()
    ui.setupUi(Autho)
    Autho.show()
    sys.exit(app.exec_())
