# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\LB2\ui\contract.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Contract(object):
    def setupUi(self, Contract):
        Contract.setObjectName("Contract")
        Contract.resize(800, 250)
        self.centralwidget = QtWidgets.QWidget(Contract)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboPatient = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboPatient.setFont(font)
        self.comboPatient.setObjectName("comboPatient")
        self.gridLayout.addWidget(self.comboPatient, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.numberContract = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numberContract.setFont(font)
        self.numberContract.setObjectName("numberContract")
        self.gridLayout.addWidget(self.numberContract, 0, 1, 1, 1)
        self.createDate = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.createDate.setFont(font)
        self.createDate.setObjectName("createDate")
        self.gridLayout.addWidget(self.createDate, 2, 1, 1, 1)
        self.totalCost = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.totalCost.setFont(font)
        self.totalCost.setObjectName("totalCost")
        self.gridLayout.addWidget(self.totalCost, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonDelete = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonDelete.setFont(font)
        self.buttonDelete.setObjectName("buttonDelete")
        self.horizontalLayout.addWidget(self.buttonDelete)
        self.buttonChange = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonChange.setFont(font)
        self.buttonChange.setObjectName("buttonChange")
        self.horizontalLayout.addWidget(self.buttonChange)
        self.buttonAdd = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonAdd.setFont(font)
        self.buttonAdd.setObjectName("buttonAdd")
        self.horizontalLayout.addWidget(self.buttonAdd)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        Contract.setCentralWidget(self.centralwidget)

        self.retranslateUi(Contract)
        QtCore.QMetaObject.connectSlotsByName(Contract)

    def retranslateUi(self, Contract):
        _translate = QtCore.QCoreApplication.translate
        Contract.setWindowTitle(_translate("Contract", "MainWindow"))
        self.label.setText(_translate("Contract", "Номер контрака"))
        self.label_2.setText(_translate("Contract", "Итог"))
        self.label_5.setText(_translate("Contract", "Пациент"))
        self.buttonDelete.setText(_translate("Contract", "Удалить"))
        self.buttonChange.setText(_translate("Contract", "Изменить"))
        self.buttonAdd.setText(_translate("Contract", "Добавить"))
        self.label_3.setText(_translate("Contract", "Дата"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Contract = QtWidgets.QMainWindow()
    ui = Ui_Contract()
    ui.setupUi(Contract)
    Contract.show()
    sys.exit(app.exec_())
