# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\LB2\ui\contractAdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContractAdd(object):
    def setupUi(self, ContractAdd):
        ContractAdd.setObjectName("ContractAdd")
        ContractAdd.resize(800, 410)
        self.centralwidget = QtWidgets.QWidget(ContractAdd)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 391))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBack = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonBack.setFont(font)
        self.buttonBack.setObjectName("buttonBack")
        self.horizontalLayout.addWidget(self.buttonBack)
        self.buttonAdd = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonAdd.setFont(font)
        self.buttonAdd.setObjectName("buttonAdd")
        self.horizontalLayout.addWidget(self.buttonAdd)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 2)
        self.createDate = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.createDate.setFont(font)
        self.createDate.setObjectName("createDate")
        self.gridLayout.addWidget(self.createDate, 2, 1, 1, 1)
        self.totalCost = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.totalCost.setFont(font)
        self.totalCost.setObjectName("totalCost")
        self.gridLayout.addWidget(self.totalCost, 1, 1, 1, 1)
        self.comboPatient = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboPatient.setFont(font)
        self.comboPatient.setObjectName("comboPatient")
        self.gridLayout.addWidget(self.comboPatient, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.numberContract = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numberContract.setFont(font)
        self.numberContract.setObjectName("numberContract")
        self.gridLayout.addWidget(self.numberContract, 0, 1, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout.addWidget(self.listWidget_2, 4, 0, 1, 2)
        ContractAdd.setCentralWidget(self.centralwidget)

        self.retranslateUi(ContractAdd)
        QtCore.QMetaObject.connectSlotsByName(ContractAdd)

    def retranslateUi(self, ContractAdd):
        _translate = QtCore.QCoreApplication.translate
        ContractAdd.setWindowTitle(_translate("ContractAdd", "MainWindow"))
        self.label.setText(_translate("ContractAdd", "Номер контрака"))
        self.label_5.setText(_translate("ContractAdd", "Пациент"))
        self.label_2.setText(_translate("ContractAdd", "Итог"))
        self.buttonBack.setText(_translate("ContractAdd", "Назад"))
        self.buttonAdd.setText(_translate("ContractAdd", "Добавить"))
        self.label_3.setText(_translate("ContractAdd", "Дата"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ContractAdd = QtWidgets.QMainWindow()
    ui = Ui_ContractAdd()
    ui.setupUi(ContractAdd)
    ContractAdd.show()
    sys.exit(app.exec_())
