# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\pythonProject\ui\History.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_History(object):
    def setupUi(self, History):
        History.setObjectName("History")
        History.resize(900, 800)
        History.setMinimumSize(QtCore.QSize(900, 800))
        History.setMaximumSize(QtCore.QSize(900, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("..\\pythonProject\\ui\\bank_78392.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        History.setWindowIcon(icon)
        History.setStyleSheet("background: rgb(34,106,170)")
        self.centralwidget = QtWidgets.QWidget(History)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 881, 781))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255,255,255)")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.name_account = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name_account.setFont(font)
        self.name_account.setStyleSheet("color: rgb(255,255,255)")
        self.name_account.setObjectName("name_account")
        self.gridLayout.addWidget(self.name_account, 1, 0, 1, 1)
        self.list_history = QtWidgets.QListWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.list_history.setFont(font)
        self.list_history.setStyleSheet("color: rgb(255,255,255)")
        self.list_history.setObjectName("list_history")
        self.gridLayout.addWidget(self.list_history, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menu_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.menu_button.setFont(font)
        self.menu_button.setStyleSheet("color: rgb(255,255,255)")
        self.menu_button.setObjectName("menu_button")
        self.horizontalLayout_2.addWidget(self.menu_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        History.setCentralWidget(self.centralwidget)

        self.retranslateUi(History)
        QtCore.QMetaObject.connectSlotsByName(History)

    def retranslateUi(self, History):
        _translate = QtCore.QCoreApplication.translate
        History.setWindowTitle(_translate("History", "History"))
        self.label.setText(_translate("History", "История:"))
        self.menu_button.setText(_translate("History", "Меню"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    History = QtWidgets.QMainWindow()
    ui = Ui_History()
    ui.setupUi(History)
    History.show()
    sys.exit(app.exec_())
