# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\pythonProject\ui\Money.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Money(object):
    def setupUi(self, Money):
        Money.setObjectName("Money")
        Money.resize(400, 250)
        Money.setMinimumSize(QtCore.QSize(400, 250))
        Money.setMaximumSize(QtCore.QSize(400, 250))
        Money.setStyleSheet("background: rgb(34,106,170)")
        self.gridLayoutWidget = QtWidgets.QWidget(Money)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_accounting_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add_accounting_button.setFont(font)
        self.add_accounting_button.setStyleSheet("color: rgb(255,255,255)")
        self.add_accounting_button.setObjectName("add_accounting_button")
        self.horizontalLayout.addWidget(self.add_accounting_button)
        self.chanel_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chanel_button.setFont(font)
        self.chanel_button.setStyleSheet("color: rgb(255,255,255)")
        self.chanel_button.setObjectName("chanel_button")
        self.horizontalLayout.addWidget(self.chanel_button)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 2)
        self.name_account = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name_account.setFont(font)
        self.name_account.setStyleSheet("color: rgb(255,255,255)")
        self.name_account.setObjectName("name_account")
        self.gridLayout.addWidget(self.name_account, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255,255,255)")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.balance = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.balance.setFont(font)
        self.balance.setStyleSheet("color: rgb(255,255,255)")
        self.balance.setObjectName("balance")
        self.gridLayout.addWidget(self.balance, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)

        self.retranslateUi(Money)
        QtCore.QMetaObject.connectSlotsByName(Money)

    def retranslateUi(self, Money):
        _translate = QtCore.QCoreApplication.translate
        Money.setWindowTitle(_translate("Money", "Выбор счета списания"))
        self.add_accounting_button.setText(_translate("Money", "Списать"))
        self.chanel_button.setText(_translate("Money", "Отмена"))
        self.label.setText(_translate("Money", "Выберите счет:"))
        self.balance.setText(_translate("Money", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Money = QtWidgets.QDialog()
    ui = Ui_Money()
    ui.setupUi(Money)
    Money.show()
    sys.exit(app.exec_())
